### ISSUE TITLE
Invalid api

### ISSUE THREAD

**Issue by NoNameoN-A** [erfan4lx/TelegramChannelMemberAdder#4]
Hi i have this error: 
`telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest)`
Do you know how can i solve?

**Comment by erfan4lx** [comment]
Hey dear, Use another api id and api hash for tool

**Comment by NoNameoN-A** [comment]
how can i delete actual app on my.telegram.org panel?

**Comment by erfan4lx** [comment]
It's not possible I think bro

**Comment by NoNameoN-A** [comment]
it conflicted with another phone number I used on this phone. I managed to recover the old data and solved.

**Comment by erfan4lx** [comment]
It's good :)
