### ISSUE TITLE
[ERROR] UsersTooMuchError

### ISSUE THREAD

**Issue by kobasis12** [erfan4lx/TelegramChannelMemberAdder#7]
Please help, i get error.
![Screenshot_1](https://user-images.githubusercontent.com/81455315/122634053-32f72a00-d106-11eb-9667-29807d323ff0.png)

Thanks before

**Comment by erfan4lx** [comment]
Hey, yes your channel have more than 200 members, and on Telegram if a channel have more than 200 members there is a limit for add members to that from Telegram and it's not possible. Good luck

**Comment by kobasis12** [comment]
Oohhhh i see. Thanks a lot bro for answer my questions.
Do you have a telegram group? For discuss about python maybe

Sab, 19 Jun 2021 pukul 15.58 erfan4lx ***@***.***> menulis:

**Comment by erfan4lx** [comment]
Of course I have put pro adder tool for group without any limit for sell, if you want you can contact me on Telegram : @erfan4lx or via Email : erfan4lx@gmail.com

**Comment by kobasis12** [comment]
Dude, is there any bot to lock the channel messages? Like bot anti-share
messages, to protect channel from "impostor" member

Sel, 22 Jun 2021 pukul 15.32 erfan4lx ***@***.***> menulis:

**Comment by erfan4lx** [comment]
Hey no I don't know really, sorry

**Comment by kobasis12** [comment]
Dude, i got problem from ur code

Here i attach screenshot

Sab, 3 Jul 2021 pukul 13.35 erfan4lx ***@***.***> menulis:

**Comment by erfan4lx** [comment]
Hey yes send screenshot !

**Comment by kobasis12** [comment]
Kam, 15 Jul 2021 pukul 00.46 erfan4lx ***@***.***> menulis:

**Comment by kobasis12** [comment]
Sorry, this better screenshot



Kam, 15 Jul 2021 pukul 08.59 Adhitya Wahyu ***@***.***>
menulis:

**Comment by erfan4lx** [comment]
I'm couldn't to see it! send me on Telegram please !

**Comment by kobasis12** [comment]
Sure. What your telegram id bro?

Kam, 15 Jul 2021 pukul 15.06 erfan4lx ***@***.***> menulis:

**Comment by erfan4lx** [comment]
@erfan4lx
